language: python
python:
- '3.6'
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev
install:
- pip install -r tests/requirements.txt
script:
- export IS_TEST=true
- export PYTHONPATH=$PYTHONPATH:.
- py.test -v -s --cov=sla/ tests/test_sla.py
after_success:
- codecov -t $CODECOV_TOKEN
