language: python
python:
- '3.6'
cache: pip
install:
- pip install -r tests/requirements.txt
script:
- export IS_TEST=true
- export PYTHONPATH=$PYTHONPATH:.
- py.test -v -s --cov=sla/ tests/test_sla.py
env:
  global:
