language: python
services:
  - docker
python:
- '3.6'
cache: pip
addons:
  apt:
    packages:
      - docker-ce
env:
  - NODE_VERSION="10.16.0"
before_install:
  - nvm install $NODE_VERSION
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev
  - docker run -d --restart=always --name skale-mysql -e MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD -e MYSQL_DATABASE=db_skale -e MYSQL_USER=$DB_USER -e MYSQL_PASSWORD=$DB_PASSWORD -v $TRAVIS_BUILD_DIR/test_data/init.sql:/docker-entrypoint-initdb.d/init.sql -p 3307:3306  mysql/mysql-server:5.7
  - docker -v
  - cd test_data
  - bash ./run_geth.sh
  - cd $TRAVIS_BUILD_DIR/test_data
  - bash ./deploy_sc.sh
  - sudo mkdir -p /skale_vol/contracts_info
  - yes |cp $TRAVIS_BUILD_DIR/test_data/skale-manager/data/unique.json /skale_vol/contracts_info/manager.json
  - cd $TRAVIS_BUILD_DIR
install:
- pip install -r tests/requirements.txt
before_script:
  - "flake8 ."
script:
- export IS_TEST=true
- export PYTHONPATH=$PYTHONPATH:.
- py.test -v -s --cov=./ tests/

after_success:
- codecov -t $CODECOV_TOKEN
