name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      MANAGER_BRANCH: "develop"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install docker and libs
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev build-essential
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install codecov pytest-cov
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Deploy manager contracts
      run: |
        bash ./test_data/create_environment.sh
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python tests/integration/prepare_validator.py
        ENV=DEV py.test -v -s --cov=./ tests/ --cov-report term-missing
    - name: Codecov
      run: |
        codecov -t $CODECOV_TOKEN
